CREATE DATABASE SistemaEscola;

CREATE TABLE TURMA (
    TUR_CODIGO Integer PRIMARY KEY AUTO_INCREMENT,
    TUR_ENSINO Varchar(25),
    TUR_NOME VARCHAR(25),
    TUR_ANO Integer,
    TUR_QUANTIDADE Integer
)ENGINE=INNODB;

CREATE TABLE ALUNO (
    ALU_MATRICULA Integer PRIMARY KEY AUTO_INCREMENT,
    ALU_NOME Varchar(255),
    ALU_ANO_NASCIMENTO Integer,
    ALU_PCD Integer,
    FK_TURMA_TUR_CODIGO Integer
)ENGINE=INNODB;
 
ALTER TABLE ALUNO ADD CONSTRAINT FK_ALUNO_2
    FOREIGN KEY (FK_TURMA_TUR_CODIGO)
    REFERENCES TURMA (TUR_CODIGO)
    ON DELETE RESTRICT;