/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AlunoController;
import controller.TurmaController;
import dominio.Turma;
import dominio.Aluno;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author savio
 */
public class telaRelacionarAluno extends javax.swing.JFrame {
    Turma turma;
    AlunoController controllerAluno = new AlunoController();
    TurmaController controllerTurma = new TurmaController();
    /**
     * Creates new form telaRelacionarAluno
     */
    public telaRelacionarAluno() {
        initComponents();
    }
    
    public telaRelacionarAluno(Turma t) {
        initComponents();
        turma = t;
        preencherTurma();
        preencherTabelaAlunos(new Aluno());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGPCD = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        txtTurmaNome = new javax.swing.JTextField();
        txtTurmaCodigo = new javax.swing.JTextField();
        txtTurmaAno = new javax.swing.JTextField();
        txtTurmaEnsino = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaAlunosTurma = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jRBSim = new javax.swing.JRadioButton();
        txtAlunoMatricula = new javax.swing.JTextField();
        jRBNao = new javax.swing.JRadioButton();
        txtAlunoNome = new javax.swing.JTextField();
        txtAlunoAno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jBBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaBuscaAluno = new javax.swing.JTable();
        jRbAmbos = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jBCadastrarAluno = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtTurmaQuantidade = new javax.swing.JTextField();
        jBRemover = new javax.swing.JButton();

        setTitle("TELA MANUTENÇÃO DA TURMA");

        jLabel4.setText("ANO:");

        jLabel11.setText("MODELO DE ENSINO");

        jLabel2.setText("CÓDIGO: ");

        jLabel3.setText("NOME:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TELA MANUTENÇÃO DA TURMA");

        tabelaAlunosTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MATRÍCULA", "NOME", "ANO", "DEFICIENTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaAlunosTurma);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("BUSCAR ALUNO"));

        bGPCD.add(jRBSim);
        jRBSim.setText("SIM");

        bGPCD.add(jRBNao);
        jRBNao.setText("NÃO");

        jLabel5.setText("MATRÍCULA:");

        jLabel6.setText("NOME:");

        jLabel7.setText("ANO DE NASCIMENTO:");

        jLabel8.setText("ALUNO COM DEFICIÊNCIA:");

        jBBuscar.setText("BUSCAR");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        tabelaBuscaAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MATRÍCULA", "NOME", "ANO", "DEFICIENTE", "TURMA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaBuscaAluno.setMaximumSize(new java.awt.Dimension(455, 360));
        tabelaBuscaAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaBuscaAluno);
        if (tabelaBuscaAluno.getColumnModel().getColumnCount() > 0) {
            tabelaBuscaAluno.getColumnModel().getColumn(4).setResizable(false);
            tabelaBuscaAluno.getColumnModel().getColumn(4).setHeaderValue("TURMA");
        }

        bGPCD.add(jRbAmbos);
        jRbAmbos.setText("AMBOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(53, 53, 53)
                        .addComponent(txtAlunoMatricula))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(82, 82, 82)
                        .addComponent(txtAlunoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBBuscar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRBSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRBNao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRbAmbos))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAlunoAno, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAlunoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAlunoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAlunoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jRBSim)
                    .addComponent(jRBNao)
                    .addComponent(jRbAmbos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel9.setText("ALUNOS DA TURMA");

        jBCadastrarAluno.setText("ADICIONAR ALUNO A TURMA");
        jBCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarAlunoActionPerformed(evt);
            }
        });

        jLabel10.setText("QUANTIDADE:");

        jBRemover.setText("REMOVER ALUNO DA TURMA");
        jBRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTurmaNome, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(txtTurmaCodigo)
                            .addComponent(txtTurmaAno)))
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTurmaEnsino)
                            .addComponent(txtTurmaQuantidade))))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jBRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCadastrarAluno)
                .addGap(169, 169, 169))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTurmaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTurmaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTurmaAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtTurmaEnsino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtTurmaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCadastrarAluno)
                    .addComponent(jBRemover))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        Aluno a = new Aluno();
        a.setMatricula(!txtAlunoMatricula.getText().isEmpty() ? Integer.parseInt(txtAlunoMatricula.getText()) : null);
        a.setNome(!txtAlunoNome.getText().isEmpty() ? txtAlunoNome.getText() : null);
        if(jRBSim.isSelected()){
            a.setPCD(1);
        }else if(jRBNao.isSelected()){
            a.setPCD(0);
        }else{
            jRbAmbos.setSelected(true);
        }
        a.setAnoNascimento(!txtAlunoAno.getText().isEmpty() ? Integer.parseInt(txtAlunoAno.getText()) : null);
        preencherTabelaAlunos(a);
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarAlunoActionPerformed
        Integer matricula = (Integer.parseInt(tabelaBuscaAluno.getValueAt(tabelaBuscaAluno.getSelectedRow(), 0).toString()));
        Aluno aluno = controllerAluno.buscarAlunoPorMatricula(matricula);
        
        if(aluno.getTurma() == null){
            //Alterando quantidade turma
            System.out.println("Quantidade Antes:" + turma.getQuantidade().toString());
            turma.setQuantidade(turma.getQuantidade()+1);
            controllerTurma.atualizarCadastro(turma);
            
            System.out.println("Quantidade Depois:" + turma.getQuantidade().toString()); 
            //Alterando turma do aluno
            aluno.setTurma(turma);
            controllerAluno.atualizarCadastro(aluno);
            preencherTurma();
            preencherTabelaAlunos(new Aluno());
            return;
        }
        
        if(aluno.getTurma().getCodigo().equals(turma.getCodigo())){
            JOptionPane.showMessageDialog(null,"Aluno já cadastrado nessa turma");
            return;
        }
        
        if(aluno.getTurma().getCodigo() != null){
            int opcao = JOptionPane.showConfirmDialog(null,"Aluno já cadastrado na turma "+ turma.getNome()+ ". Deseja cadastrar nessa nova turma?");
            
            if(opcao == 0){
                //Alterando quantidade turma antiga
                aluno.getTurma().setQuantidade(aluno.getTurma().getQuantidade()-1);
                controllerTurma.atualizarCadastro(aluno.getTurma());
                
                //Alterando quantidade turma nova
                turma.setQuantidade(turma.getQuantidade()+1);
                controllerTurma.atualizarCadastro(turma);
                
                //Alterando turma do aluno
                aluno.setTurma(turma);
                controllerAluno.atualizarCadastro(aluno);
                JOptionPane.showMessageDialog(null,"Cadastros realizado com sucesso!");
                preencherTurma();
                preencherTabelaAlunos(new Aluno());
                return;
            }else{
                JOptionPane.showMessageDialog(null,"Operação cancelada");
            }
            JOptionPane.showMessageDialog(null,"Operação não realizada");
        }
    }//GEN-LAST:event_jBCadastrarAlunoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jBRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemoverActionPerformed
        Integer matricula = (Integer.parseInt(tabelaAlunosTurma.getValueAt(tabelaAlunosTurma.getSelectedRow(), 0).toString()));
        Aluno aluno = controllerAluno.buscarAlunoPorMatricula(matricula);
        
        int opcao = JOptionPane.showConfirmDialog(null,"Deseja remover o aluno "+ aluno.getNome()+ " da turma "+ turma.getNome()+" ?");
        
        if(opcao == 0){
            System.out.println("Quantidade Antes:" + aluno.getTurma().getQuantidade().toString());
            turma.setQuantidade(turma.getQuantidade()-1);
            controllerTurma.atualizarCadastro(turma);
            System.out.println("Quantidade Depois:" + aluno.getTurma().getQuantidade().toString());
            
            aluno.setTurma(null);
            controllerAluno.atualizarCadastro(aluno);
            JOptionPane.showMessageDialog(null,"Aluno removido com sucesso!");
            
            preencherTurma();
            preencherTabelaAlunos(new Aluno());
        }else{
            JOptionPane.showMessageDialog(null,"Operação não realizada");
        }
    }//GEN-LAST:event_jBRemoverActionPerformed

    private void preencherTurma() {
        txtTurmaCodigo.setText(turma.getCodigo().toString());
        txtTurmaAno.setText(turma.getAno().toString());
        txtTurmaEnsino.setText(turma.getEnsino());
        txtTurmaNome.setText(turma.getNome());
        txtTurmaQuantidade.setText(turma.getQuantidade().toString());
        
        preencherTabelaAlunosTurma();
    }
    
     public void preencherTabelaAlunosTurma(){
        try {
            List<Aluno> lista = controllerAluno.buscarTodosAlunosTurma(turma);
            DefaultTableModel modelo=(DefaultTableModel)tabelaAlunosTurma.getModel();
            modelo.setNumRows(0);
            
            for(Aluno aluno: lista){
                modelo.addRow(new Object[]{
                    aluno.getMatricula(),
                    aluno.getNome(),
                    aluno.getAnoNascimento(),
                    aluno.getPCD() == 1 ? "Sim" : "Não"
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Erro ao Listar"+e);
        }
    }
    
    public void preencherTabelaAlunos(Aluno a){
        try {
            List<Aluno> lista = controllerAluno.buscarAlunosFiltrado(a);
            DefaultTableModel modelo=(DefaultTableModel)tabelaBuscaAluno.getModel();
            modelo.setNumRows(0);
            
            for(Aluno aluno: lista){
                modelo.addRow(new Object[]{
                    aluno.getMatricula(),
                    aluno.getNome(),
                    aluno.getAnoNascimento(),
                    aluno.getPCD() == 1 ? "Sim" : "Não",
                    aluno.getTurma() != null ? aluno.getTurma().getNome(): ""
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Erro ao Listar"+e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGPCD;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCadastrarAluno;
    private javax.swing.JButton jBRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBNao;
    private javax.swing.JRadioButton jRBSim;
    private javax.swing.JRadioButton jRbAmbos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaAlunosTurma;
    private javax.swing.JTable tabelaBuscaAluno;
    private javax.swing.JTextField txtAlunoAno;
    private javax.swing.JTextField txtAlunoMatricula;
    private javax.swing.JTextField txtAlunoNome;
    private javax.swing.JTextField txtTurmaAno;
    private javax.swing.JTextField txtTurmaCodigo;
    private javax.swing.JTextField txtTurmaEnsino;
    private javax.swing.JTextField txtTurmaNome;
    private javax.swing.JTextField txtTurmaQuantidade;
    // End of variables declaration//GEN-END:variables
}
