/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AlunoController;
import dao.TurmaDao;
import dominio.Aluno;
import dominio.Turma;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author savio
 */
public class telaAluno extends javax.swing.JInternalFrame {

    AlunoController controller = new AlunoController();
    Aluno aluno = null;
    JDesktopPane desktop;

    /**
     * Creates new form telaAluno
     */
    public telaAluno() {
        initComponents();
        //this.setLocationRelativeTo(null);
        this.txtMatricula.setEnabled(false);
        this.txtNomeTurma.setEnabled(false);
        this.txtCodigoturma.setEnabled(false);
    }

    public telaAluno(Aluno aluno) {
        initComponents();
        //this.setLocationRelativeTo(null);
        this.aluno = aluno;
        this.txtMatricula.setEnabled(false);
        this.txtCodigoturma.setEditable(false);
        this.txtNomeTurma.setEditable(false);

        preencherTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGpcd = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBvoltar = new javax.swing.JButton();
        jBCadastrar = new javax.swing.JButton();
        jBAtualizar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        txtMatricula = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtAnoNascimento = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigoturma = new javax.swing.JTextField();
        txtNomeTurma = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRBSim = new javax.swing.JRadioButton();
        jRBNao = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("MATRÍCULA:");

        jLabel3.setText("NOME:");

        jLabel4.setText("ANO DE NASCIMENTO:");

        jBvoltar.setText("VOLTAR");
        jBvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvoltarActionPerformed(evt);
            }
        });

        jBCadastrar.setText("CADASTRAR");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jBAtualizar.setText("ATUALIZAR");
        jBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizarActionPerformed(evt);
            }
        });

        jBExcluir.setText("EXCLUIR");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TELA ALUNO");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DETALHES DA TURMA"));

        jLabel5.setText("CODIGO:");

        jLabel6.setText("NOME:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeTurma)
                    .addComponent(txtCodigoturma))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCodigoturma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("ALUNO COM DEFICIÊNCIA:");

        bGpcd.add(jRBSim);
        jRBSim.setText("SIM");

        bGpcd.add(jRBNao);
        jRBNao.setText("NÃO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jBCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(jBAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(jBExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome)
                            .addComponent(txtMatricula)
                            .addComponent(txtAnoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(38, 38, 38)
                        .addComponent(jRBSim)
                        .addGap(41, 41, 41)
                        .addComponent(jRBNao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jBvoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAnoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jRBSim)
                    .addComponent(jRBNao))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrar)
                    .addComponent(jBAtualizar)
                    .addComponent(jBExcluir))
                .addGap(18, 18, 18)
                .addComponent(jBvoltar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBvoltarActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed

        try {
            Integer.parseInt(txtAnoNascimento.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ano de nascimento inválido!");
            return;
        }

        Aluno aluno = new Aluno();
        aluno.setNome(txtNome.getText());
        aluno.setAnoNascimento(Integer.parseInt(txtAnoNascimento.getText()));

        if (jRBSim.isSelected()) {
            aluno.setPCD(1);
        } else if (jRBNao.isSelected()) {
            aluno.setPCD(0);
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todas as informações.");
            return;
        }

        TurmaDao turmadao = new TurmaDao();

        if (txtCodigoturma.getText().isEmpty()) {
            aluno.setTurma(null);
        } else {
            Turma turma = turmadao.buscarTurmaPorCodigo(Integer.parseInt(txtCodigoturma.getText()));
            aluno.setTurma(turma);
        }

        aluno = controller.cadastrarAluno(aluno);

        if (aluno.getMatricula() != null) {
            JOptionPane.showMessageDialog(null, "Aluno cadastrado com Sucesso!");
            voltar();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar Aluno!");
        }
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarActionPerformed

        try {
            Integer.parseInt(txtAnoNascimento.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ano de nascimento inválido!");
            return;
        }

        Aluno aluno = new Aluno();
        aluno.setMatricula(Integer.parseInt(txtMatricula.getText()));
        aluno.setNome(txtNome.getText());
        aluno.setAnoNascimento(Integer.parseInt(txtAnoNascimento.getText()));

        if (jRBSim.isSelected()) {
            aluno.setPCD(1);
        } else if (jRBNao.isSelected()) {
            aluno.setPCD(0);
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todas as informações.");
            return;
        }
        TurmaDao turmadao = new TurmaDao();

        if (txtCodigoturma.getText().isEmpty()) {
            aluno.setTurma(null);
        } else {
            Turma turma = turmadao.buscarTurmaPorCodigo(Integer.parseInt(txtCodigoturma.getText()));
            aluno.setTurma(turma);
        }

        controller.atualizarCadastro(aluno);

        if (aluno.getMatricula() != null) {
            JOptionPane.showMessageDialog(null, "Aluno atualizado com Sucesso!");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao atualizar Aluno!");
        }
    }//GEN-LAST:event_jBAtualizarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        Aluno aluno = null;
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja remover o(a) aluno(a) " + txtNome.getText()+ " ?");
        aluno = controller.removerAluno(Integer.parseInt(txtMatricula.getText()));
        try {
            if (opcao == 0) {
                if (aluno != null) {
                    JOptionPane.showMessageDialog(null, "Registro excluído com Sucesso!");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao excluir Registro!");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Operação não realizada");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Existem alunos na turma");
        }
        
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void preencherTela() {
        txtAnoNascimento.setText(aluno.getAnoNascimento().toString());
        txtMatricula.setText(aluno.getMatricula().toString());
        txtNome.setText(aluno.getNome());
        if (aluno.getPCD() == 0) {
            jRBNao.setSelected(true);
        }
        if (aluno.getPCD() == 1) {
            jRBSim.setSelected(true);
        }

        if (aluno.getTurma() != null) {
            txtNomeTurma.setText(aluno.getTurma().getNome());
            txtCodigoturma.setText(aluno.getTurma().getCodigo().toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGpcd;
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBvoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBNao;
    private javax.swing.JRadioButton jRBSim;
    private javax.swing.JTextField txtAnoNascimento;
    private javax.swing.JTextField txtCodigoturma;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeTurma;
    // End of variables declaration//GEN-END:variables

    public void voltar() {
        telaCadastro telaC = new telaCadastro();
        telaPrincipal.desktopPane.add(telaC);
        telaC.setVisible(true);
        this.dispose();
    }
}
