/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;

/**
 *
 * @author savio
 */
public class telaCadastro extends javax.swing.JInternalFrame {   

    /**
     * Creates new form telaCadastro
     */
    public telaCadastro() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbCadastrarAluno = new javax.swing.JButton();
        jbCadastrarTurma = new javax.swing.JButton();
        jBButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbCadastrarAluno.setText("CADASTRAR ALUNO");
        jbCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarAlunoActionPerformed(evt);
            }
        });

        jbCadastrarTurma.setText("CADASTRAR TURMA");
        jbCadastrarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarTurmaActionPerformed(evt);
            }
        });

        jBButton.setText("VOLTAR");
        jBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbCadastrarTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbCadastrarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jbCadastrarAluno)
                .addGap(44, 44, 44)
                .addComponent(jbCadastrarTurma)
                .addGap(42, 42, 42)
                .addComponent(jBButton)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarAlunoActionPerformed
        telaAluno telaA = new telaAluno();
        telaPrincipal.desktopPane.add(telaA);
        telaA.setVisible(true);
        
    }//GEN-LAST:event_jbCadastrarAlunoActionPerformed

    private void jbCadastrarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarTurmaActionPerformed
        telaTurma telaT = new telaTurma();
        telaPrincipal.desktopPane.add(telaT);
        telaT.setVisible(true);
        

    }//GEN-LAST:event_jbCadastrarTurmaActionPerformed

    private void jBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBButton;
    private javax.swing.JButton jbCadastrarAluno;
    private javax.swing.JButton jbCadastrarTurma;
    // End of variables declaration//GEN-END:variables
}
